spring.application.name=exemplo_02_spring

spring.jpa.open-in-view=true

# H2 Connection Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# H2 Client Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL Show Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
